// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Diagnostics.CodeAnalysis;

using Microsoft.EntityFrameworkCore;

namespace CRUDExercises.EF.Entities;

[Table("CLIENT")]
public partial class Client
{
    [Key]
    [Column("ID")]
    public int Id { get; set; }

    [Required]
    [Column("NOM")]
    [StringLength(50)]
    public string Nom { get; set; }

    [Required]
    [Column("PRENOM")]
    [StringLength(50)]
    public string Prenom { get; set; }

    [Column("DATE_NAISSANCE")]
    public DateTime Date_Naissance { get; set; }

    [Column("ADRESSE")]
    [StringLength(150)]
    public string? Adresse { get; set; }

    [Column("CODE_POSTAL")]
    [StringLength(15)]
    public string? Code_Postal { get; set; }

    [Column("VILLE")]
    [StringLength(50)]
    public string? Ville { get; set; }

    [InverseProperty("IdClientNavigation")]
    public virtual ICollection<Location> Locations { get; set; } = new List<Location>();

	public Client() { }

	public Client(int id,
                    string firstName,
                    string lastName,
                    DateTime birthDate,
                    string? address,
                    string? postalCode,
                    string? city)
    {
        Id = id;
        Nom = lastName;
        Prenom = firstName;
        Date_Naissance = birthDate;
        Adresse = address;
        Code_Postal = postalCode;
        Ville = city;
    }
}