// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CRUDExercises.EF.Entities;

[Table("LOCATION")]
public partial class Location
{
    [Key]
    [Column("ID")]
    public int Id { get; set; }

    [Column("ID_CLIENT")]
    public int? Id_Client { get; set; }

    [Column("ID_VEHICULE")]
    public int? Id_Vehicule { get; set; }

    [Column("NB_KM")]
    public int Nb_Km { get; set; }

    [Column("DATE_DEBUT")]
    public DateTime Date_Debut { get; set; }

    [Column("DATE_FIN")]
    public DateTime? Date_Fin { get; set; }

    [ForeignKey("Id_Client")]
    [InverseProperty("Locations")]
    public virtual Client IdClientNavigation { get; set; }

	public Location() { }

	public Location(int id,
                    int? idClient,
                    int? idVehicule,
                    int nbKm,
                    DateTime dateDebut,
                    DateTime? dateFin)
    {
        Id = id;
        Id_Client = idClient;
        Id_Vehicule = idVehicule;
        Nb_Km = nbKm;
        Date_Debut = dateDebut;
        Date_Fin = dateFin;
    }
}